### ISSUE TITLE
Reset with error of certain class

### ISSUE THREAD

**Issue by aleksandr-oleynikov** [vitalets/promise-controller#1]
Hello!

If you call `.reset()` and promise is pending it will be rejected with error which will be instance of common class `Error`.
It leads to difficulties with processing errors. If you want to detect such type of promise rejection reason you have to check message `Promise rejected by reset`.

My offer is to reject promise with error of certain class. `RejectError` for example. And put it into PromiseController scope.
So errors processing will be looked like this:
```javascript
var promise = promiseController.call(...);
...
promise
    .catch(error => {
            if (error instanceof PromiseController.ResetError) {
                console.log('promise controller was reset');
            } else {
                throw error;
            }
    })
```

Now I need to call `.reject()` with my custom error instead of using method `.reset()` to process errors such way.

**Comment by vitalets** [comment]
Hi!
Currently there is constructor option [`resetReason`](https://github.com/vitalets/promise-controller#options--object) that defines the error for `.reset()`. Now it can only be a string. I think it should accept error or function to allow developer to set any own Error class. As well as `timeoutReason` does.

Adding `PromiseController.ResetError` looks also reasonable, because it requires less configuration. 
I think I will also add both `PromiseController.ResetError` and `PromiseController.TimeoutError` for default case.

**Comment by aleksandr-oleynikov** [comment]
> I think I will also add both `PromiseController.ResetError` and `PromiseController.TimeoutError` for default case.

It would be great!
I will be looking forward to this improvements.
